map $http_upgrade $tapgo_dsh_connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 443 ssl http2;
    server_name dsh-macmini.itapgo.com;
    ssl_certificate /etc/letsencrypt/live/tapgo-dsh-mobile/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tapgo-dsh-mobile/privkey.pem;
    access_log off;
    location / {
        proxy_pass http://127.0.0.1:19401;
        include /www/server/panel/vhost/nginx/tapgo-dsh-proxy.inc;
    }
}

server {
    listen 443 ssl http2;
    server_name dsh-jkmini.itapgo.com;
    ssl_certificate /etc/letsencrypt/live/tapgo-dsh-mobile/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tapgo-dsh-mobile/privkey.pem;
    access_log off;
    location / {
        proxy_pass http://127.0.0.1:19402;
        include /www/server/panel/vhost/nginx/tapgo-dsh-proxy.inc;
    }
}

server {
    listen 443 ssl http2;
    server_name dsh-macbook.itapgo.com;
    ssl_certificate /etc/letsencrypt/live/tapgo-dsh-mobile/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tapgo-dsh-mobile/privkey.pem;
    access_log off;
    location / {
        proxy_pass http://127.0.0.1:19403;
        include /www/server/panel/vhost/nginx/tapgo-dsh-proxy.inc;
    }
}
